# based on the template from
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

image: maven:3.6-jdk-11

cache:
  paths:
    - .m2/repository

# For merge requests do not `deploy` but only run `verify`.
.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS generate-sources'
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master

# Verify merge requests
verify:jdk11:
  <<: *verify

# deploy using ci_settings.xml as maven settings
# see https://gitlab.com/help/user/packages/maven_repository/index.md#creating-maven-packages-with-gitlab-cicd-using-maven
deploy:jdk11:
  script:
    - 'mvn generate-sources -s ci_settings.xml'
    - 'mvn verify -s ci_settings.xml'
    - mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout
  artifacts:
    paths:
      - bindings/target
      - oxygen/target
  only:
    - master
    - tags


pages:
  image: busybox:latest
  stage: deploy
  script:
    - mkdir -p public
    - ls -la
    - cp -v oxygen/target/*-plugin.jar public/
    - cp -v oxygen/target/descriptor.xml public/
  artifacts:
    paths:
      - public
  only:
    # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27818
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
